name: Build and push to gcr

on:
  workflow_dispatch:  # Allows manual triggering of this workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}  # Your GCP service account key

    - name: Build and Push duck-shipping-worker Image
      run: |
        docker buildx build --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/duck-shipping-worker:latest -f duck-shipping-worker/Dockerfile duck-shipping-worker/

    - name: Build and Push duck-analytics-worker Image
      run: |
        docker buildx build --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/duck-analytics-worker:latest -f duck-analytics-worker/Dockerfile duck-analytics-worker/

    - name: Build and Push duck-aggregator-worker Image
      run: |
        docker buildx build --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/duck-aggregator-worker:latest -f duck-aggregator-worker/Dockerfile duck-aggregator-worker/

    - name: Build and Push order-ducks Image
      run: |
        docker buildx build --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/order-ducks:latest -f order-ducks/Dockerfile order-ducks/

    - name: Build and Push proxy-server Image
      run: |
        docker buildx build --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/proxy-server:latest -f proxy-server/Dockerfile proxy-server/
    
    - name: Build and Push duck-db
      run: |
        docker buildx build --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/duck-db:latest -f duck-db/Dockerfile duck-db/

    - name: Build and Push duck-queue
      run: |
        docker buildx build --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/duck-queue:latest -f duck-queue/Dockerfile duck-queue/
