name: Build and push to Docker Hub

on:
  workflow_dispatch:  # Allows manual triggering of this workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push duck-shipping-worker Image
      run: |
        docker buildx build --push -t mreider/duck-shipping-worker:latest -f duck-shipping-worker/Dockerfile duck-shipping-worker/

    - name: Build and Push duck-analytics-worker Image
      run: |
        docker buildx build --push -t mreider/duck-analytics-worker:latest -f duck-analytics-worker/Dockerfile duck-analytics-worker/

    - name: Build and Push duck-aggregator-worker Image
      run: |
        docker buildx build --push -t mreider/duck-aggregator-worker:latest -f duck-aggregator-worker/Dockerfile duck-aggregator-worker/

    - name: Build and Push order-ducks Image
      run: |
        docker buildx build --push -t mreider/order-ducks:latest -f order-ducks/Dockerfile order-ducks/

    - name: Build and Push proxy-server Image
      run: |
        docker buildx build --push -t mreider/proxy-server:latest -f proxy-server/Dockerfile proxy-server/
    
    - name: Build and Push duck-db
      run: |
        docker buildx build --push -t mreider/duck-db:latest -f duck-db/Dockerfile duck-db/

    - name: Build and Push duck-queue
      run: |
        docker buildx build --push -t mreider/duck-queue:latest -f duck-queue/Dockerfile duck-queue/
